org: happyfine
app: priyannka
service: project1
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  environment:
    STUDENT_DATA_TABLE: studentsData
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:311141554419:table/studentsData  # Correct table name

  apiGateway:
    restApiName: StudentAPI  # Explicit API Gateway definition
    description: "API for student data"

functions:
  ui:
    handler: ui.handler
    events:
      - http:
          path: /
          method: get
          cors: true

  getStudents:
    handler: getStudents.lambda_handler
    events:
      - http:
          path: students
          method: get
          cors: true

  insertStudentData:
    handler: insertStudentData.lambda_handler
    events:
      - http:
          path: students
          method: post
          cors: true

resources:
  Resources:
    StudentDataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: studentsData  # Ensure correct table name
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: studentid
            AttributeType: S
        KeySchema:
          - AttributeName: studentid
            KeyType: HASH
